Lekkerbek.Web/Models/Entities/Customer.cs
using Lekkerbek.Web.Models.Enums;
using Microsoft.AspNetCore.Identity;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Lekkerbek.Web.Models.Entities
{
  public class Customer : Person
  {
    [DisplayName("Bestellingen")]
    public virtual ICollection<Order> Orders { get; set; }

    [DisplayName("Voorkeur")]
    public FoodCategory? FoodPreference { get; set; }

    [ForeignKey("Company")]
    public int? CompanyId { get; set; }
    public virtual Company Company { get; set; }

    [DefaultValue(false)]
    [Display(Name = "Professionele klant?")]
    public bool IsProfessional { get; set; }

    public string? IdentityUserId { get; set; }

    public IdentityUser? IdentityUser { get; set; }
    }
}

Lekkerbek.Web/ViewModels/Cooks/DetailsViewModel.cs
using Lekkerbek.Web.Models.Entities;
using Microsoft.AspNetCore.Identity;
using System.ComponentModel;

namespace Lekkerbek.Web.ViewModels.Cooks
{
    public class DetailsViewModel
    {
        [DisplayName("Tijdslot")]
        public virtual ICollection<TimeSlot> TimeSlots { get; set; }
        [DefaultValue(false)]
        public int Id { get; set; }

        [DisplayName("Voornaam")]
        public string FirstName { get; set; }

        [DisplayName("Familienaam")]
        public string LastName { get; set; }

        [DisplayName("Naam")]
        public string Name { get { return FirstName + " " + LastName; } }

        [DisplayName("Geboortedatum")]
        public DateTime BirthDate { get; set; }

        [DisplayName("Adres")]
        public string Adress { get; set; }

        [DisplayName("E-mail")]
        public string Email { get; set; }

        [DisplayName("Telefoonnummer")]
        public string PhoneNumber { get; set; }
        public bool IsDeleted { get; set; }
        public string IdentityUserId { get; set; }
        public IdentityUser IdentityUser { get; set; }
    }
}

Lekkerbek.Web/ViewModels/Customers/CustomerViewModel.cs
namespace Lekkerbek.Web.ViewModels.Customers
{
    public class CustomerViewModel
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
    }
}

Lekkerbek.Web/ViewModels/Customers/DeleteViewModel.cs
using Lekkerbek.Web.Models.Entities;
using Lekkerbek.Web.Models.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace Lekkerbek.Web.ViewModels.Customers
{
    public class DeleteViewModel
    {
        public int Id { get; set; }

        [DisplayName("Voornaam")]
        public string FirstName { get; set; }

        [DisplayName("Familienaam")]
        public string LastName { get; set; }

        [DisplayName("Naam")]
        public string Name { get { return FirstName + " " + LastName; } }

        [DisplayName("Geboortedatum")]
        public DateTime BirthDate { get; set; }

        [DisplayName("Adres")]
        public string Adress { get; set; }

        [DisplayName("E-mail")]
        public string Email { get; set; }

        [DisplayName("Telefoonnummer")]
        public string PhoneNumber { get; set; }

        [DisplayName("Bestellingen")]
        public virtual ICollection<Order> Orders { get; set; }

        [DisplayName("Voorkeur")]
        public FoodCategory? FoodPreference { get; set; }

        [DisplayName("Firma")]
        public virtual Company? Company { get; set; }

        [DefaultValue(false)]
        [Display(Name = "Professionele klant?")]
        public bool IsProfessional { get; set; }
    }
}

Lekkerbek.Web/ViewModels/Customers/DetailsViewModel.cs
using Lekkerbek.Web.Models.Entities;
using Lekkerbek.Web.Models.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace Lekkerbek.Web.ViewModels.Customers
{
    public class DetailsViewModel
    {
        public int Id { get; set; }

        [DisplayName("Voornaam")]
        public string FirstName { get; set; }

        [DisplayName("Familienaam")]
        public string LastName { get; set; }

        [DisplayName("Naam")]
        public string Name { get { return FirstName + " " + LastName; } }

        [DisplayName("Geboortedatum")]
        public DateTime BirthDate { get; set; }

        [DisplayName("Adres")]
        public string Adress { get; set; }

        [DisplayName("E-mail")]
        public string Email { get; set; }

        [DisplayName("Telefoonnummer")]
        public string PhoneNumber { get; set; }

        [DisplayName("Bestellingen")]
        public virtual ICollection<Order> Orders { get; set; }

        [DisplayName("Voorkeur")]
        public FoodCategory? FoodPreference { get; set; }

        [DisplayName("Firma")]
        public virtual Company? Company { get; set; }

        [DefaultValue(false)]
        [Display(Name = "Professionele klant?")]
        public bool IsProfessional { get; set; }
    }
}

Lekkerbek.Web/ViewModels/Customers/IndexViewModel.cs
using Lekkerbek.Web.Models.Entities;
using Lekkerbek.Web.Models.Enums;
using Microsoft.AspNetCore.Identity;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Lekkerbek.Web.ViewModels.Customers
{
    public class IndexViewModel
    {
        public int Id { get; set; }

        [DisplayName("Voornaam")]
        public string FirstName { get; set; }

        [DisplayName("Familienaam")]
        public string LastName { get; set; }

        [DisplayName("Naam")]
        public string Name { get { return FirstName + " " + LastName; } }

        [DisplayName("Geboortedatum")]
        public DateTime BirthDate { get; set; }

        [DisplayName("Geboortedatum")]
        public string BirthdayString { get { return BirthDate.ToString("dd/MM/yyyy"); } }

        [DisplayName("Adres")]
        public string Adress { get; set; }

        [DisplayName("E-mail")]
        public string Email { get; set; }

        [DisplayName("Telefoonnummer")]
        public string PhoneNumber { get; set; }

        [DisplayName("Bestellingen")]
        public virtual ICollection<Order> Orders { get; set; }

        [DisplayName("Voorkeur")]
        public FoodCategory? FoodPreference { get; set; }

        [DisplayName("Firma")]
        public virtual Company? Company { get; set; }

        [DefaultValue(false)]
        [Display(Name = "Professionele klant?")]
        public bool IsProfessional { get; set; }

        public string? IdentityUserId { get; set; }

        public IdentityUser? IdentityUser { get; set; }
    }
}

Lekkerbek.Web/ViewModels/Orders/CreateViewModel.cs
using Lekkerbek.Web.Models.Entities;
using Lekkerbek.Web.Models.Enums;
using Lekkerbek.Web.ViewModels.Customers;
using Lekkerbek.Web.ViewModels.Products;
using System.ComponentModel.DataAnnotations;

namespace Lekkerbek.Web.ViewModels.Orders
{
    public class CreateViewModel
    {
        [Display(Name = "Klant")]
        public int CustomerId { get; set; }

        [Display(Name = "Tijdslot")]
        public int TimeSlotId { get; set; }

        [Display(Name = "Betaalwijze")]
        public virtual PaymentProcessor? PaymentProcessor { get; set; }

        [Display(Name = "Bestelstatus")]
        public virtual OrderStatus OrderStatus { get; set; }

        [Display(Name = "Bijkomende opmerkingen")]
        public string? ExtraComments { get; set; }

        public List<Customer> ViewCustomers { get; set; }

        public List<CustomerViewModel> SelectListCreate { get; set; }

        public List<IGrouping<Cook, TimeSlot>> ViewTimeSlots { get; set; } = new List<IGrouping<Cook, TimeSlot>>();

        public List<ProductViewModel> DishIdList { get; set; }

        public List<ProductViewModel> NonAlcoholicIdList { get; set; }

        public List<ProductViewModel> AlcoholicIdList { get; set; }

    }
}

Lekkerbek.Web/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lekkerbek.Web.Data;
using Lekkerbek.Web.Models.Entities;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Lekkerbek.Web.Services;
using Microsoft.AspNetCore.Authorization;
using Lekkerbek.Web.ViewModels.Customers;
using System.Security.Claims;

namespace Lekkerbek.Web.Controllers
{
    [Authorize(Roles = "Clerk, Customer, Super, Administrator")]
    public class CustomersController : Controller
    {
        //private readonly LekkerbekDbContext _context;
        private readonly ICustomerService _customerService;

        public CustomersController(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            var customers = await _customerService.GetCustomers();

            List<IndexViewModel> customersVMList = new List<IndexViewModel>();

            foreach (var item in customers)
            {
                IndexViewModel customerVM = new IndexViewModel
                {
                    Id = item.Id,
                    FirstName = item.FirstName,
                    LastName = item.LastName,
                    BirthDate = item.BirthDate,
                    Adress = item.Adress,
                    Email = item.Email,
                    PhoneNumber = item.PhoneNumber,
                    Orders = item.Orders,
                    FoodPreference = item.FoodPreference,
                    Company = item.Company,
                    IsProfessional = item.IsProfessional, 
                    IdentityUserId = item.IdentityUserId
                };
                customersVMList.Add(customerVM);
            }
            if (User.IsInRole("Administrator") || User.IsInRole("Clerk") || User.IsInRole("Super"))
            {
                return View(customersVMList);
            } else
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                return View(customersVMList.Where(c => c.IdentityUserId == userId));
            }
        }
        // Kendo Table Customers Index
        public async Task<IActionResult> GetCustomers([DataSourceRequest] DataSourceRequest request)
        {
            var kendolekkerbekDbContextCustomers = await _customerService.GetCustomers();

            List<IndexViewModel> customersVMList = new List<IndexViewModel>();

            foreach (var item in kendolekkerbekDbContextCustomers)
            {
                IndexViewModel customerVM = new IndexViewModel
                {
                    Id = item.Id,
                    FirstName = item.FirstName,
                    LastName = item.LastName,
                    BirthDate = item.BirthDate,
                    Adress = item.Adress,
                    Email = item.Email,
                    PhoneNumber = item.PhoneNumber,
                    Orders = item.Orders,
                    FoodPreference = item.FoodPreference,
                    Company = item.Company,
                    IsProfessional = item.IsProfessional
                };
                customersVMList.Add(customerVM);
            }

            JsonResult result = Json(customersVMList.ToDataSourceResult(request));
            return result;
        }

        // GET: Customers/Details/5

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || await _customerService.GetCustomers() == null)
            {
                return NotFound();
            }

            var customerDetail = await _customerService.GetCustomer(id);

            if (customerDetail == null)
            {
                return NotFound();
            }

            DetailsViewModel customerVM = new DetailsViewModel
            {
                Id = customerDetail.Id,
                FirstName = customerDetail.FirstName,
                LastName = customerDetail.LastName,
                BirthDate = customerDetail.BirthDate,
                Adress = customerDetail.Adress,
                Email = customerDetail.Email,
                PhoneNumber = customerDetail.PhoneNumber,
                Orders = customerDetail.Orders,
                FoodPreference = customerDetail.FoodPreference,
                Company = customerDetail.Company,
                IsProfessional = customerDetail.IsProfessional
            };

            return View(customerVM);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FoodPreference,Id,FirstName,LastName,BirthDate,Adress,Email,PhoneNumber")] Customer customer)
        {
            try
            {
                await _customerService.CreateCustomer(customer);
                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(Create));
            }
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || await _customerService.GetCustomers() == null)
            {
                return NotFound();
            }

            var customer = await _customerService.GetCustomer(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FoodPreference,Id,FirstName,LastName,BirthDate,Adress,Email,PhoneNumber")] Customer customer)
        {
            if (id != customer.Id)
            {
                return NotFound();
            }

            try
            {
                await _customerService.EditCustomer(customer);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                if (!CustomerExists(customer.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || await _customerService.GetCustomers() == null)
            {
                return NotFound();
            }

            var customerGetDelete = await _customerService.GetCustomer(id);

            if (customerGetDelete == null)
            {
                return NotFound();
            }

            DeleteViewModel customerVM = new DeleteViewModel
            {
                Id = customerGetDelete.Id,
                FirstName = customerGetDelete.FirstName,
                LastName = customerGetDelete.LastName,
                BirthDate = customerGetDelete.BirthDate,
                Adress = customerGetDelete.Adress,
                Email = customerGetDelete.Email,
                PhoneNumber = customerGetDelete.PhoneNumber,
                Orders = customerGetDelete.Orders,
                FoodPreference = customerGetDelete.FoodPreference,
                Company = customerGetDelete.Company,
                IsProfessional = customerGetDelete.IsProfessional
            };

            return View(customerVM);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            if (await _customerService.GetCustomers() == null)
            {
                return Problem("Entity set 'LekkerbekDbContext.Customers'  is null.");
            }

            var customerPostDelete = await _customerService.DeleteCustomer(id);

            if (customerPostDelete != null)
            {
                return RedirectToAction(nameof(Index));
            }

            var customerGetDelete = await _customerService.GetCustomer(id);

            DeleteViewModel customerVM = new DeleteViewModel
            {
                Id = customerGetDelete.Id,
                FirstName = customerGetDelete.FirstName,
                LastName = customerGetDelete.LastName,
                BirthDate = customerGetDelete.BirthDate,
                Adress = customerGetDelete.Adress,
                Email = customerGetDelete.Email,
                PhoneNumber = customerGetDelete.PhoneNumber,
                Orders = customerGetDelete.Orders,
                FoodPreference = customerGetDelete.FoodPreference,
                Company = customerGetDelete.Company,
                IsProfessional = customerGetDelete.IsProfessional
            };

            return View(customerVM);

        }

        private bool CustomerExists(int id)
        {
            return _customerService.CustomerExist(id);
        }
    }
}

Lekkerbek.Web/Views/Customers/Create.cshtml
@model Lekkerbek.Web.Models.Entities.Customer

@{
    ViewData["Title"] = "Aanmaken klant";
}

<h1>Aanmaken</h1>

<h4>Klant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FoodPreference" class="control-label"></label>
                <select asp-for="FoodPreference" asp-items="@Html.GetEnumSelectList<Lekkerbek.Web.Models.Enums.FoodCategory>()" class="form-control">
                    <option value="" selected>Geen voorkeur</option>
                </select>
                <span asp-validation-for="FoodPreference" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Aanmaken" class="btn btn-primary mt-2" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Terug naar de lijst</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lekkerbek.Web/Views/Customers/Delete.cshtml
@model Lekkerbek.Web.ViewModels.Customers.DeleteViewModel

@{
    ViewData["Title"] = "Verwijderen klant";
}

<h1>Verwijderen</h1>

<div>
    <h4>@Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FoodPreference)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FoodPreference)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Verwijderen" class="btn btn-danger" /> |
        <a asp-action="Index">Terug naar de lijst</a>
    </form>
</div>

Lekkerbek.Web/Views/Customers/Details.cshtml
@model Lekkerbek.Web.ViewModels.Customers.DetailsViewModel

@{
    ViewData["Title"] = "Details klant";
}

<h1>Details</h1>

<div>
    <h4>@Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FoodPreference)
        </dt>
        <dd class = "col-sm-10">
            @{
                if (Model.FoodPreference == null)
                {
                    <label>Geen voorkeur</label>
                }
            }
            @Html.DisplayFor(model => model.FoodPreference)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Aanpassen</a> |
    <a asp-action="Index">Terug naar de lijst</a>
</div>

Lekkerbek.Web/Views/Customers/Edit.cshtml
@model Lekkerbek.Web.Models.Entities.Customer

@{
    ViewData["Title"] = "Aanpassen klant";
}

<h1>Aanpassen</h1>

<h4>@Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FoodPreference" class="control-label"></label>
                <select asp-for="FoodPreference" asp-items="@Html.GetEnumSelectList<Lekkerbek.Web.Models.Enums.FoodCategory>()" class="form-control">
                    <option value="" selected>Geen voorkeur</option>
                </select>
                <span asp-validation-for="FoodPreference" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Bewaren" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Terug naar de lijst</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lekkerbek.Web/Views/Customers/Index.cshtml
@model IEnumerable<Lekkerbek.Web.ViewModels.Customers.IndexViewModel>

@using Kendo.Mvc.UI;

@{
    ViewData["Title"] = "Overzicht klanten";
}

<h1>Overzicht klanten</h1>

<p>
    <a asp-action="Create">Nieuwe klant aanmaken</a>
</p>

<div class="form-group">
    @(
        Html.Kendo().Grid<Lekkerbek.Web.ViewModels.Customers.IndexViewModel>(Model)
        .Name("grid")
        .Columns(columns =>
        {
            columns.Bound(p => p.Id);
            columns.Bound(p => p.FoodPreference);
            columns.Bound(p => p.FirstName);
            columns.Bound(p => p.LastName);
            columns.Bound(p => p.BirthdayString);
            columns.Bound(p => p.Adress);
            columns.Bound(p => p.Email);
            columns.Bound(p => p.PhoneNumber);
            columns.Bound(p => p.Id).Width(116).Title(" ").ClientTemplate(
            "<a class='k-button k-button-md k-rounded-md k-button-solid k-button-solid-base m-1' href='" +
            Url.Action("Edit", "Customers") +
            "/#= Id #'" + "><span class='k-icon k-i-edit'></span></a>" +
            "<a class='k-button k-button-md k-rounded-md k-button-solid k-button-solid-base m-1' href='" +
            Url.Action("Delete", "Customers") +
            "/#= Id #'" + "><span class='k-icon k-i-delete'></span></a>"
            );
        })
        .HtmlAttributes(new { style = "height: auto;" })
        .Pageable(pageable => pageable
        .Refresh(true)
        .PageSizes(true)
        .ButtonCount(5))
        .DataSource(dataSource => dataSource
        .Ajax()
        .Read(read => read.Action("GetCustomers", "Customers"))
        .Model(model => model.Id(d => d.Id))
        .PageSize(5)
        )
        .Events(e => e.DataBound("onDataBound"))
        )
</div>

<script>
    function onDataBound() {
        $('#grid table tr').dblclick(function (e) {
            var grid = $("#grid").data("kendoGrid");
            var row = $(this);

            var dItem = grid.dataItem(row);
            if (dItem != null) {
                var id = dItem.Id;
                window.location.href = "@Url.Action("Details", "Customers")" + "?id=" + id;
            }
        });
    }
</script>