Lekkerbek.Web/Models/Entities/Company.cs
using System.ComponentModel;

namespace Lekkerbek.Web.Models.Entities
{
    public class Company
    {
        public int Id { get; set; }
        [DisplayName("Firma")]
        public string Name { get; set; }
        [DisplayName("BTW-nummer")]
        public string VatNumber { get; set; }
        [DisplayName("ContactpersoonId")]
        public int ContactPersonId { get; set; }
        [DisplayName("Contactpersoon")]
        public virtual Customer ContactPerson { get; set; }
    }
}

Lekkerbek.Web/ViewModels/Companies/IndexViewModel.cs
using System.ComponentModel;

namespace Lekkerbek.Web.ViewModels.Companies
{
    public class IndexViewModel
    {
        public int Id { get; set; }
        [DisplayName("Firma")]
        public string Name { get; set; }
        [DisplayName("BTW-nummer")]
        public string VatNumber { get; set; }
        [DisplayName("Contactpersoon")]
        public int ContactPersonId { get; set; }
        [DisplayName("Contactpersoon")]
        public string ContactName { get; set; }
    }
}

Lekkerbek.Web/ViewModels/Cooks/DetailsViewModel.cs
using Lekkerbek.Web.Models.Entities;
using Microsoft.AspNetCore.Identity;
using System.ComponentModel;

namespace Lekkerbek.Web.ViewModels.Cooks
{
    public class DetailsViewModel
    {
        [DisplayName("Tijdslot")]
        public virtual ICollection<TimeSlot> TimeSlots { get; set; }
        [DefaultValue(false)]
        public int Id { get; set; }

        [DisplayName("Voornaam")]
        public string FirstName { get; set; }

        [DisplayName("Familienaam")]
        public string LastName { get; set; }

        [DisplayName("Naam")]
        public string Name { get { return FirstName + " " + LastName; } }

        [DisplayName("Geboortedatum")]
        public DateTime BirthDate { get; set; }

        [DisplayName("Adres")]
        public string Adress { get; set; }

        [DisplayName("E-mail")]
        public string Email { get; set; }

        [DisplayName("Telefoonnummer")]
        public string PhoneNumber { get; set; }
        public bool IsDeleted { get; set; }
        public string IdentityUserId { get; set; }
        public IdentityUser IdentityUser { get; set; }
    }
}

Lekkerbek.Web/ViewModels/Customers/DeleteViewModel.cs
using Lekkerbek.Web.Models.Entities;
using Lekkerbek.Web.Models.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace Lekkerbek.Web.ViewModels.Customers
{
    public class DeleteViewModel
    {
        public int Id { get; set; }

        [DisplayName("Voornaam")]
        public string FirstName { get; set; }

        [DisplayName("Familienaam")]
        public string LastName { get; set; }

        [DisplayName("Naam")]
        public string Name { get { return FirstName + " " + LastName; } }

        [DisplayName("Geboortedatum")]
        public DateTime BirthDate { get; set; }

        [DisplayName("Adres")]
        public string Adress { get; set; }

        [DisplayName("E-mail")]
        public string Email { get; set; }

        [DisplayName("Telefoonnummer")]
        public string PhoneNumber { get; set; }

        [DisplayName("Bestellingen")]
        public virtual ICollection<Order> Orders { get; set; }

        [DisplayName("Voorkeur")]
        public FoodCategory? FoodPreference { get; set; }

        [DisplayName("Firma")]
        public virtual Company? Company { get; set; }

        [DefaultValue(false)]
        [Display(Name = "Professionele klant?")]
        public bool IsProfessional { get; set; }
    }
}

Lekkerbek.Web/ViewModels/Customers/DetailsViewModel.cs
using Lekkerbek.Web.Models.Entities;
using Lekkerbek.Web.Models.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace Lekkerbek.Web.ViewModels.Customers
{
    public class DetailsViewModel
    {
        public int Id { get; set; }

        [DisplayName("Voornaam")]
        public string FirstName { get; set; }

        [DisplayName("Familienaam")]
        public string LastName { get; set; }

        [DisplayName("Naam")]
        public string Name { get { return FirstName + " " + LastName; } }

        [DisplayName("Geboortedatum")]
        public DateTime BirthDate { get; set; }

        [DisplayName("Adres")]
        public string Adress { get; set; }

        [DisplayName("E-mail")]
        public string Email { get; set; }

        [DisplayName("Telefoonnummer")]
        public string PhoneNumber { get; set; }

        [DisplayName("Bestellingen")]
        public virtual ICollection<Order> Orders { get; set; }

        [DisplayName("Voorkeur")]
        public FoodCategory? FoodPreference { get; set; }

        [DisplayName("Firma")]
        public virtual Company? Company { get; set; }

        [DefaultValue(false)]
        [Display(Name = "Professionele klant?")]
        public bool IsProfessional { get; set; }
    }
}

Lekkerbek.Web/ViewModels/Orders/CreateViewModel.cs
using Lekkerbek.Web.Models.Entities;
using Lekkerbek.Web.Models.Enums;
using Lekkerbek.Web.ViewModels.Customers;
using Lekkerbek.Web.ViewModels.Products;
using System.ComponentModel.DataAnnotations;

namespace Lekkerbek.Web.ViewModels.Orders
{
    public class CreateViewModel
    {
        [Display(Name = "Klant")]
        public int CustomerId { get; set; }

        [Display(Name = "Tijdslot")]
        public int TimeSlotId { get; set; }

        [Display(Name = "Betaalwijze")]
        public virtual PaymentProcessor? PaymentProcessor { get; set; }

        [Display(Name = "Bestelstatus")]
        public virtual OrderStatus OrderStatus { get; set; }

        [Display(Name = "Bijkomende opmerkingen")]
        public string? ExtraComments { get; set; }

        public List<Customer> ViewCustomers { get; set; }

        public List<CustomerViewModel> SelectListCreate { get; set; }

        public List<IGrouping<Cook, TimeSlot>> ViewTimeSlots { get; set; } = new List<IGrouping<Cook, TimeSlot>>();

        public List<ProductViewModel> DishIdList { get; set; }

        public List<ProductViewModel> NonAlcoholicIdList { get; set; }

        public List<ProductViewModel> AlcoholicIdList { get; set; }

    }
}

Lekkerbek.Web/ViewModels/Orders/DetailsViewModel.cs
using Lekkerbek.Web.Models.Entities;
using Lekkerbek.Web.Models.Enums;
using Lekkerbek.Web.ViewModels.OrderLines;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Lekkerbek.Web.ViewModels.Orders
{
    public class DetailsViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Aanmaakdatum")]
        public DateTime CreationDate { get; set; }

        [Display(Name = "Bijkomende opmerkingen")]
        public string? ExtraComments { get; set; }

        [Display(Name = "Tijdslot")]
        public DateTime StartTime { get; set; }

        [Display(Name = "Klant")]
        public string Name { get; set; }

        [Display(Name = "Betaalwijze")]
        public virtual PaymentProcessor? PaymentProcessor { get; set; }

        [DefaultValue(false)]
        [Display(Name = "Getrouwheidskorting")]
        public bool HasDiscount { get; set; }

        [Display(Name = "Bestelstatus")]
        public virtual OrderStatus OrderStatus { get; set; }

        public Order Order { get; set; }

        [Range(0, int.MaxValue)]
        public decimal TotalPrice { get; set; }

        public List<OrderLineViewModel> OrderLineList { get; set; }

        public bool CanBeEdited { get; set; }

        public bool IsProfessional { get; set; }

        [DisplayName("Firma")]
        public string CompanyName { get; set; }
        [DisplayName("BTW-nummer")]
        public string VatNumber { get; set; }

    }
}

Lekkerbek.Web/ViewModels/Orders/EditViewModel.cs
using Lekkerbek.Web.Models.Entities;
using Lekkerbek.Web.Models.Enums;
using Lekkerbek.Web.ViewModels.Customers;
using Lekkerbek.Web.ViewModels.Products;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace Lekkerbek.Web.ViewModels.Orders
{
    public class EditViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Klant")]
        public int CustomerId { get; set; }

        [Display(Name = "Tijdslot")]
        public int TimeSlotId { get; set; }

        [Display(Name = "Betaalwijze")]
        public virtual PaymentProcessor? PaymentProcessor { get; set; }

        [Display(Name = "Bestelstatus")]
        public virtual OrderStatus OrderStatus { get; set; }

        [Display(Name = "Bijkomende opmerkingen")]
        public string? ExtraComments { get; set; }

        public Order Order { get; set; }

        public List<Customer> ViewCustomers { get; set; }

        public List<CustomerViewModel> SelectListCreate { get; set; }

        public List<IGrouping<Cook, TimeSlot>> ViewTimeSlots { get; set; } = new List<IGrouping<Cook, TimeSlot>>();

        public List<ProductViewModel> ProductsIdList { get; set; }

        public string? EditAlert { get; set; }

    }
}

Lekkerbek.Web/ViewModels/Timeslots/DetailsViewModel.cs
using Lekkerbek.Web.Models.Entities;
using System.ComponentModel;

namespace Lekkerbek.Web.ViewModels.Timeslots
{
    public class DetailsViewModel
    {
        public int Id { get; set; }
        [DisplayName("Starttijd")]
        public DateTime StartTime { get; set; }

        [DefaultValue(false)]
        [DisplayName("Bezet")]
        public bool IsOccupied { get; set; }

        [DisplayName("Kok")]
        public string CookFirstName { get; set; }

        [DisplayName("Bestelling")]
        public int OrderId { get; set; }
        [DisplayName("Bijkomende opmerkingen")]
        public string? OrderExtraComments { get; set; }
    }
}

Lekkerbek.Web/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lekkerbek.Web.Data;
using Lekkerbek.Web.Models.Entities;
using Lekkerbek.Web.Services;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using Microsoft.AspNetCore.Authorization;
using Lekkerbek.Web.ViewModels.Companies;

namespace Lekkerbek.Web.Controllers
{
    [Authorize(Roles = "Clerk, Super, Administrator")]
    public class CompaniesController : Controller
    {
        private readonly ICompanyService _companyService;
        private readonly IContactPersonService _contactPersonService;

        public CompaniesController(ICompanyService company, IContactPersonService contactPersonService)
        {
            _companyService = company;
            _contactPersonService = contactPersonService;
        }

        // GET: Companies
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Customer"))
            {
                return Unauthorized();
            }
            var companies = await _companyService.GetCompanies();
            var companiesViewModels = companies.Select(c => new IndexViewModel() { Id = c.Id, ContactPersonId = c.ContactPersonId, ContactName = c.ContactPerson.FullName, Name = c.Name, VatNumber = c.VatNumber }).ToList();
            return View(companiesViewModels);
        }

        // Kendo Table Company Index
        public async Task<IActionResult> GetCompanies([DataSourceRequest] DataSourceRequest request)
        {
            var companies = await _companyService.GetCompanies();
            var companiesViewModels = companies.Select(c => new IndexViewModel() { Id = c.Id, ContactPersonId = c.ContactPersonId/*, ContactName = c.ContactPerson.FullName*/, Name = c.Name, VatNumber = c.VatNumber }).ToList();
            JsonResult result = Json(companiesViewModels.ToDataSourceResult(request));
            return result;
        }

        // GET: Companies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Company company;
            try
            {
                company = await _companyService.GetCompany(id);
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception)
            {

                throw;
            }

            return View(company);
        }

        // GET: Companies/Create
        public async Task<IActionResult> Create()
        {
            var contactPersonViewModel = await _contactPersonService.GetContactPersons();
            ViewData["ContactPersonId"] = new SelectList(contactPersonViewModel.Where(cp => cp.Company == null).Select(cp => new { Id = cp.Id, ViewText = $"{cp.FirstName} {cp.LastName}" }), "Id", "ViewText");
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,VatNumber,ContactPersonId")] Company company)
        {
            try
            {
                await _companyService.CreateCompany(company);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                var contactPersonViewModel = await _contactPersonService.GetContactPersons();
                ViewData["ContactPersonId"] = new SelectList(contactPersonViewModel.Select(cp => new { Id = cp.Id, ViewText = $"{cp.FirstName} {cp.LastName}" }), "Id", "ViewText");
                return View(company);
            }
        }

        public async Task<IActionResult> CreateContactPerson()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateContactPerson([Bind("FoodPreference,Id,FirstName,LastName,BirthDate,Adress,Email,PhoneNumber")] Customer customer)
        {
            try
            {
                await _contactPersonService.CreateContactPerson(customer);
                return RedirectToAction(nameof(Index));

            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Create));
            }
        }

        // GET: Companies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || await _companyService.GetCompanies() == null)
            {
                return NotFound();
            }

            var company = await _companyService.GetCompany(id);
            if (company == null)
            {
                return NotFound();
            }
            var contactPersonViewModel = await _contactPersonService.GetContactPersons();
            ViewData["ContactPersonId"] = new SelectList(contactPersonViewModel.Select(cp => new { Id = cp.Id, ViewText = $"{cp.FirstName} {cp.LastName}" }), "Id", "ViewText");
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,VatNumber,ContactPersonId")] Company company)
        {
            if (id != company.Id)
            {
                return NotFound();
            }

            try
            {
                await _companyService.EditCompany(company);
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CompanyExists(company.Id))
                {
                    return NotFound();
                }
                else
                {
                    var contactPersonViewModel = await _contactPersonService.GetContactPersons();
                    ViewData["ContactPersonId"] = new SelectList(contactPersonViewModel.Select(cp => new { Id = cp.Id, ViewText = $"{cp.FirstName} {cp.LastName}" }), "Id", "ViewText");
                    return View(company);
                }
            }
        }

        // GET: Companies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || await _companyService.GetCompanies() == null)
            {
                return NotFound();
            }

            var company = await _companyService.GetCompany(id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (await _companyService.GetCompanies() == null)
            {
                return Problem("Entity set 'LekkerbekDbContext.Companies'  is null.");
            }
            var company = await _companyService.GetCompany(id);
            if (company != null)
            {
                await _companyService.DeleteCompany(company);
                return RedirectToAction(nameof(Index));
            }
            return View(company);

        }
        private bool CompanyExists(int id)
        {
            return _companyService.CompanyExist(id);
        }
    }
}

Lekkerbek.Web/Views/Companies/Create.cshtml
@model Lekkerbek.Web.Models.Entities.Company

@{
    ViewData["Title"] = "Aanmaken firma";
}

<h1>Aanmaken</h1>

<h4>Firma</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VatNumber" class="control-label"></label>
                <input asp-for="VatNumber" class="form-control" />
                <span asp-validation-for="VatNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactPersonId" class="control-label"></label>
                <select asp-for="ContactPersonId" class="form-control" asp-items="ViewBag.ContactPersonId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Aanmaken" class="btn btn-primary mt-2" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Terug naar de lijst</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lekkerbek.Web/Views/Companies/CreateContactPerson.cshtml
@model Lekkerbek.Web.Models.Entities.Customer

@{
    ViewData["Title"] = "Aanmaken Professionele Klant";
}

<h1>Aanmaken</h1>

<h4>Klant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateContactPerson">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FoodPreference" class="control-label"></label>
                <select asp-for="FoodPreference" asp-items="@Html.GetEnumSelectList<Lekkerbek.Web.Models.Enums.FoodCategory>()" class="form-control">
                    <option value="" selected>Geen voorkeur</option>
                </select>
                <span asp-validation-for="FoodPreference" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Aanmaken" class="btn btn-primary mt-2" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Terug naar de lijst</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Lekkerbek.Web/Views/Companies/Delete.cshtml
@model Lekkerbek.Web.Models.Entities.Company

@{
    ViewData["Title"] = "Verwijderen firma";
}

<h1>Verwijderen</h1>

<h3>Bent u zeker dat u deze firma wilt verwijderen?</h3>
<div>
    <h4>Firma</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VatNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VatNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactPerson)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactPerson.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Verwijderen" class="btn btn-danger" /> |
        <a asp-action="Index">Terug naar de lijst</a>
    </form>
</div>

Lekkerbek.Web/Views/Companies/Details.cshtml
@model Lekkerbek.Web.Models.Entities.Company

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Firma</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VatNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VatNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactPerson)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactPerson.FirstName)
            @Html.DisplayFor(model => model.ContactPerson.LastName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Terug naar de lijst</a>
</div>

Lekkerbek.Web/Views/Companies/Edit.cshtml
@model Lekkerbek.Web.Models.Entities.Company

@{
    ViewData["Title"] = "Aanpassen";
}

<h1>Aanpassen</h1>

<h4>Firma</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VatNumber" class="control-label"></label>
                <input asp-for="VatNumber" class="form-control" />
                <span asp-validation-for="VatNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactPersonId" class="control-label"></label>
                <select asp-for="ContactPersonId" class="form-control" asp-items="ViewBag.ContactPersonId"></select>
                <span asp-validation-for="ContactPersonId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Bewaren" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Terug naar de lijst</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lekkerbek.Web/Views/Companies/Index.cshtml
@using Kendo.Mvc.UI;
@model IEnumerable<Lekkerbek.Web.ViewModels.Companies.IndexViewModel>

@{
    ViewData["Title"] = "Overzicht firma's";
}

<h1>Overzicht firma's</h1>

<p><a asp-action="Create">Nieuwe firma</a></p>
<p><a asp-action="CreateContactPerson">Nieuwe contactpersoon</a></p>

<div class="form-group">
    @(
        Html.Kendo().Grid<Lekkerbek.Web.ViewModels.Companies.IndexViewModel>(Model)
        .Name("grid")
        .Columns(columns =>
        {
            columns.Bound(p => p.Name);
            columns.Bound(p => p.VatNumber);
            columns.Bound(p => p.ContactName);
            columns.Bound(p => p.Id).Width(116).Title(" ").ClientTemplate(
            "<a class='k-button k-button-md k-rounded-md k-button-solid k-button-solid-base m-1' href='" +
            Url.Action("Edit", "Companies") +
            "/#= Id #'" + "><span class='k-icon k-i-edit'></span></a>" +            
            "<a class='k-button k-button-md k-rounded-md k-button-solid k-button-solid-base m-1' href='" +
            Url.Action("Delete", "Companies") +
            "/#= Id #'" + "><span class='k-icon k-i-delete'></span></a>"
            );
        })
        .HtmlAttributes(new { style = "height: auto;" })
        .Pageable(pageable => pageable
        .Refresh(true)
        .PageSizes(true)
        .ButtonCount(5))
        .DataSource(dataSource => dataSource
        .Ajax()
        .Read(read => read.Action("GetCompanies", "Companies"))
        .Model(model => model.Id(d => d.Id))
        .PageSize(5)
        )
        .Events(e => e.DataBound("onDataBound"))
        )
</div>

<script>
    function onDataBound() {
        $('#grid table tr').dblclick(function (e) {
            var grid = $("#grid").data("kendoGrid");
            var row = $(this);

            var dItem = grid.dataItem(row);
            if (dItem != null) {
                var id = dItem.Id;
                window.location.href = "@Url.Action("Details", "Companies")" + "?id=" + id;
            }
        });
    }
</script>