Lekkerbek.Web/Controllers/CooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lekkerbek.Web.Data;
using Lekkerbek.Web.Models.Entities;
using Lekkerbek.Web.Services;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Lekkerbek.Web.ViewModels.Cooks;
using System.ComponentModel;

namespace Lekkerbek.Web.Controllers
{
    [Authorize(Roles = "Administrator, Super")]
    public class CooksController : Controller
    {
        private readonly ICookService _cookService;
        private readonly IOrderService _orderService;

        public CooksController(ICookService cookService, IOrderService orderService)
        {
            _cookService = cookService;
            _orderService = orderService;
        }

        // GET: Cooks
        public async Task<IActionResult> Index()
        {
            var cooks = await _cookService.GetCooks();
            return View(cooks);
        }

        // Kendo Table Cooks Index
        public async Task<IActionResult> GetCooks([DataSourceRequest] DataSourceRequest request)
        {
            var kendolekkerbekDbContextCooks = await _cookService.GetCooks();
            JsonResult result = Json(kendolekkerbekDbContextCooks.ToDataSourceResult(request));
            return result;
        }

        // GET: Cooks/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null || await _cookService.GetCooks() == null)
            {
                return NotFound();
            }

            var cook = await _cookService.GetCook(id);
            if (cook == null)
            {
                return NotFound();
            }

            DetailsViewModel detailsVM = new DetailsViewModel
            {
                TimeSlots = cook.TimeSlots,
                Id = cook.Id,
                FirstName = cook.FirstName,
                LastName = cook.LastName,
                BirthDate = cook.BirthDate,
                Adress = cook.Adress,
                Email = cook.Email,
                PhoneNumber = cook.PhoneNumber,
                IsDeleted = cook.IsDeleted,
                IdentityUserId = cook.IdentityUserId,
                IdentityUser = cook.IdentityUser

            };

            return View(detailsVM);
        }

        // GET: Cooks/Create

        public IActionResult Create()
        {
            return View();
        }

        // POST: Cooks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,BirthDate,Adress,Email,PhoneNumber,Password")] Cook cook)
        {
            try
            {
                await _cookService.CreateCook(cook);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(Create));
            }

        }

        // GET: Cooks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || await _cookService.GetCooks() == null)
            {
                return NotFound();
            }

            var cook = await _cookService.GetCook(id);
            if (cook == null)
            {
                return NotFound();
            }
            return View(cook);
        }

        // POST: Cooks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,BirthDate,Adress,Email,PhoneNumber")] Cook cook)
        {
            if (id != cook.Id)
            {
                return NotFound();
            }

            try
            {
                await _cookService.EditCook(cook);
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CookExists(cook.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
        }

        // GET: Cooks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || await _cookService.GetCooks() == null)
            {
                return NotFound();
            }

            var cook = await _cookService.GetCook(id);
            if (cook == null)
            {
                return NotFound();
            }

            return View(cook);
        }

        // POST: Cooks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            if (await _cookService.GetCooks() == null)
            {
                return Problem("Entity set 'LekkerbekDbContext.Cooks'  is null.");
            }
            var cook = await _cookService.GetCook(id);
            if (cook != null)
            {
                await _cookService.DeleteCook(cook);
                return RedirectToAction(nameof(Index));
            }

            return View(cook);
        }

        private bool CookExists(int id)
        {
            return _cookService.CookExist(id);
        }
    }
}

Lekkerbek.Web/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lekkerbek.Web.Data;
using System.Collections;
using Lekkerbek.Web.Models.Entities;
using Microsoft.CodeAnalysis;
using System.Net.Mail;
using System.Net;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Lekkerbek.Web.Models.Enums;
using Lekkerbek.Web.Services;
using Lekkerbek.Web.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using static NuGet.Packaging.PackagingConstants;
using Lekkerbek.Web.ViewModels.Orders;
using Lekkerbek.Web.ViewModels.Customers;
using Lekkerbek.Web.ViewModels.Products;
using Telerik.SvgIcons;
using Lekkerbek.Web.ViewModels.OrderLines;

namespace Lekkerbek.Web.Controllers
{
    [Authorize(Roles = "Customer, Clerk, Super, Administrator, Cook")]
    public class OrdersController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly ICustomerService _customerService;
        private readonly IMailService _mailService;

        public OrdersController(IOrderService orderService, ICustomerService customerService, IMailService mailService)
        {
            _orderService = orderService;
            _customerService = customerService;
            _mailService = mailService;
        }


        // GET: Orders
        [Authorize(Roles = "Customer, Clerk, Super, Administrator")]
        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var kendolekkerbekDbContextOrders = await _orderService.GetOrders();

            List<ViewModels.Orders.IndexViewModel> ordersVMList = new List<ViewModels.Orders.IndexViewModel>();
            foreach (var item in kendolekkerbekDbContextOrders)
            {
                if (User.IsInRole("Administrator") || User.IsInRole("Clerk") || User.IsInRole("Super"))
                {
                    bool canBeDeleted = false;
                    bool canBeEdited = false;
                    TimeSpan ts = item.TimeSlot.StartTime - DateTime.Now;
                    if (Math.Floor(ts.TotalMinutes) > 60)
                    {
                        canBeEdited = true;
                    }
                    if (Math.Floor(ts.TotalMinutes) > 120)
                    {
                        canBeDeleted = true;
                    }

                    ViewModels.Orders.IndexViewModel orderVM = new ViewModels.Orders.IndexViewModel
                    {
                        Id = item.Id,
                        CreationDate = item.CreationDate.ToString("dd/MM/yyyy HH:mm"),
                        ExtraComments = item.ExtraComments,
                        TimeSlotInfo = item.TimeSlot.StartTime.ToString("dd/MM/yyyy HH:mm") + " - " + item.TimeSlot.EndTime.ToString("HH:mm"),
                        Name = item.Customer.FirstName + " " + item.Customer.LastName,
                        PaymentProcessor = item.PaymentProcessor,
                        OrderStatus = item.OrderStatus,
                        HasDiscount = item.HasDiscount,
                        EditPossible = canBeEdited,
                        DeletePossible = canBeDeleted
                    };
                    ordersVMList.Add(orderVM);
                }
                else
                {
                    if (item.Customer.IdentityUserId == userId)
                    {
                        bool canBeDeleted = false;
                        bool canBeEdited = false;
                        TimeSpan ts = item.TimeSlot.StartTime - DateTime.Now;
                        if (Math.Floor(ts.TotalMinutes) > 60)
                        {
                            canBeEdited = true;
                        }
                        if (Math.Floor(ts.TotalMinutes) > 120)
                        {
                            canBeDeleted = true;
                        }

                        ViewModels.Orders.IndexViewModel orderVM = new ViewModels.Orders.IndexViewModel
                        {
                            Id = item.Id,
                            CreationDate = item.CreationDate.ToString("dd/MM/yyyy HH:mm"),
                            ExtraComments = item.ExtraComments,
                            TimeSlotInfo = item.TimeSlot.StartTime.ToString("dd/MM/yyyy HH:mm") + " - " + item.TimeSlot.EndTime.ToString("HH:mm"),
                            Name = item.Customer.FirstName + " " + item.Customer.LastName,
                            PaymentProcessor = item.PaymentProcessor,
                            OrderStatus = item.OrderStatus,
                            HasDiscount = item.HasDiscount,
                            EditPossible = canBeEdited,
                            DeletePossible = canBeDeleted,
                            IdentityUserId = userId,
                        };
                        ordersVMList.Add(orderVM);
                    }
                }
            }
            return View(ordersVMList);
        }

        // Kendo Table Orders Index
        [Authorize(Roles = "Customer, Clerk, Super, Administrator")]
        public async Task<IActionResult> GetOrders([DataSourceRequest] DataSourceRequest request)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var kendolekkerbekDbContextOrders = await _orderService.GetOrders();

            List<ViewModels.Orders.IndexViewModel> ordersVMList = new List<ViewModels.Orders.IndexViewModel>();

            foreach (var item in kendolekkerbekDbContextOrders)
            {
                if (User.IsInRole("Administrator") || User.IsInRole("Clerk") || User.IsInRole("Super"))
                {
                    bool canBeDeleted = false;
                    bool canBeEdited = false;
                    TimeSpan ts = item.TimeSlot.StartTime - DateTime.Now;
                    if (Math.Floor(ts.TotalMinutes) > 60)
                    {
                        canBeEdited = true;
                    }
                    if (Math.Floor(ts.TotalMinutes) > 120)
                    {
                        canBeDeleted = true;
                    }

                    ViewModels.Orders.IndexViewModel orderVM = new ViewModels.Orders.IndexViewModel
                    {
                        Id = item.Id,
                        CreationDate = item.CreationDate.ToString("dd/MM/yyyy HH:mm"),
                        ExtraComments = item.ExtraComments,
                        TimeSlotInfo = item.TimeSlot.StartTime.ToString("dd/MM/yyyy HH:mm") + " - " + item.TimeSlot.EndTime.ToString("HH:mm"),
                        Name = item.Customer.FirstName + " " + item.Customer.LastName,
                        PaymentProcessor = item.PaymentProcessor,
                        OrderStatus = item.OrderStatus,
                        HasDiscount = item.HasDiscount,
                        EditPossible = canBeEdited,
                        DeletePossible = canBeDeleted
                    };
                    ordersVMList.Add(orderVM);
                }
                else
                {
                    if (item.Customer.IdentityUserId == userId)
                    {
                        bool canBeDeleted = false;
                        bool canBeEdited = false;
                        TimeSpan ts = item.TimeSlot.StartTime - DateTime.Now;
                        if (Math.Floor(ts.TotalMinutes) > 60)
                        {
                            canBeEdited = true;
                        }
                        if (Math.Floor(ts.TotalMinutes) > 120)
                        {
                            canBeDeleted = true;
                        }

                        ViewModels.Orders.IndexViewModel orderVM = new ViewModels.Orders.IndexViewModel
                        {
                            Id = item.Id,
                            CreationDate = item.CreationDate.ToString("dd/MM/yyyy HH:mm"),
                            ExtraComments = item.ExtraComments,
                            TimeSlotInfo = item.TimeSlot.StartTime.ToString("dd/MM/yyyy HH:mm") + " - " + item.TimeSlot.EndTime.ToString("HH:mm"),
                            Name = item.Customer.FirstName + " " + item.Customer.LastName,
                            PaymentProcessor = item.PaymentProcessor,
                            OrderStatus = item.OrderStatus,
                            HasDiscount = item.HasDiscount,
                            EditPossible = canBeEdited,
                            DeletePossible = canBeDeleted
                        };
                        ordersVMList.Add(orderVM);
                    }
                }
            }
            JsonResult result = Json(ordersVMList.ToDataSourceResult(request));
            return result;
        }


        // GET: Orders/Details/5
        [Authorize(Roles = "Customer, Clerk, Super, Administrator, Cook")]
        public async Task<IActionResult> Details(int? id)
        {
            var tuple = await _orderService.GetDetails(id);

            if (id == null || await _orderService.GetOrders() == null)
            {
                return NotFound();
            }

            if (tuple == null)
            {
                return NotFound();
            }
            bool canBeEdited = false;
            TimeSpan ts = tuple.Item1.TimeSlot.StartTime - DateTime.Now;
            if (Math.Floor(ts.TotalMinutes) > 60)
            {
                canBeEdited = true;
            }
            List<OrderLineViewModel> orderLinelist = new List<OrderLineViewModel>();
            foreach (OrderLine o in tuple.Item4)
            {
                ViewModels.OrderLines.OrderLineViewModel orderVM = new ViewModels.OrderLines.OrderLineViewModel
                {
                    DishName = o.Dish.Name,
                    Price = o.Dish.Price,
                    Tax = o.Dish.ProductCategory.Tax,

Lekkerbek.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lekkerbek.Web</title>
    @*    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lekkerbek.Web.styles.css" asp-append-version="true" />*@

    @*Scripts & Links for Telerik*@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet"
          href="https://kendo.cdn.telerik.com/themes/6.2.0/bootstrap/bootstrap-main.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ood_les6_prep_kendo.styles.css" asp-appendversion="true" />
    <link rel="stylesheet"
          href="https://code.jquery.com/ui/1.13.0/themes/smoothness/jquery-ui.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.kendostatic.com/2023.1.314/js/kendo.all.min.js"></script>
    <script src="https://cdn.kendostatic.com/2023.1.314/js/kendo.aspnetmvc.min.js"></script>
    <script src="~/js/kendo-ui-license.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img width="150" src="img/Logo Lekkerbek.jpeg " alt="" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole("Super"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Bestellingen</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Klanten</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Companies" asp-action="Index">Firmas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="TimeSlots" asp-action="Index">Tijdsloten</a>
                            </li>
@*                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cooks" asp-action="Index">Koks</a>
                            </li>*@
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Werknemers</a>
                            </li>
                        }
                        @if (User.IsInRole("Clerk"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Bestellingen</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Klanten</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Companies" asp-action="Index">Firmas</a>
                            </li>
                        }
                        @if (User.IsInRole("Customer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Bestellingen</a>
                            </li>
                        }
                        @if (User.IsInRole("Cook"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="TimeSlots" asp-action="Index">Tijdsloten</a>
                            </li>
                        }
                        @if (User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Bestellingen</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Klanten</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Companies" asp-action="Index">Firmas</a>
                            </li>
@*                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cooks" asp-action="Index">Koks</a>
                            </li>*@
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Werknemers</a>
                            </li>
                        }
                    </ul>
                    <!--Identity Framework - shows email adress at the top of the page when logged in-->
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - De Lekkerbek@* - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
    @*    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>*@
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>