Lekkerbek.Web/ViewModels/Employees/IndexViewModel.cs
using System.ComponentModel;

namespace Lekkerbek.Web.ViewModels.Employees
{
    public class IndexViewModel
    {
        public int Id { get; set; }

        [DisplayName("Voornaam")]
        public string FirstName { get; set; }

        [DisplayName("Familienaam")]
        public string LastName { get; set; }

        [DisplayName("Naam")]
        public string Name { get { return FirstName + " " + LastName; } }

        [DisplayName("Geboortedatum")]
        public DateTime BirthDate { get; set; }

        [DisplayName("Geboortedatum")]
        public string BirthdayString { get { return BirthDate.ToString("dd/MM/yyyy"); } }

        [DisplayName("Adres")]
        public string Adress { get; set; }

        [DisplayName("E-mail")]
        public string Email { get; set; }

        [DisplayName("Telefoonnummer")]
        public string PhoneNumber { get; set; }
    }
}

Lekkerbek.Web/Controllers/EmployeesController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Lekkerbek.Web.Models.Entities;
using Lekkerbek.Web.Services;
using Lekkerbek.Web.ViewModels.Employees;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Lekkerbek.Web.Controllers
{
    [Authorize(Roles = "Administrator, Super")]
    public class EmployeesController : Controller
    {
        private readonly ICookService _cookService;
        private readonly IClerkService _clerkService;

        public EmployeesController(ICookService cookService, IClerkService clerkService)
        {
            _cookService = cookService;
            _clerkService = clerkService;
        }


        // GET: Cooks
        public async Task<IActionResult> Index()
        {
            return View();
        }

        // Kendo Table Cooks Index
        public async Task<IActionResult> GetCooks([DataSourceRequest] DataSourceRequest request)
        {
            var kendolekkerbekDbContextCooks = await _cookService.GetCooks();

            List<IndexViewModel> CooksVMList = new List<IndexViewModel>();

            foreach (var item in kendolekkerbekDbContextCooks)
            {
                IndexViewModel cooksVM = new IndexViewModel
                {
                    Id = item.Id,
                    FirstName = item.FirstName,
                    LastName = item.LastName,
                    BirthDate = item.BirthDate,
                    Adress = item.Adress,
                    Email = item.Email,
                    PhoneNumber = item.PhoneNumber,
                };
                CooksVMList.Add(cooksVM);
            }

            JsonResult result = Json(CooksVMList.ToDataSourceResult(request));
            return result;
        }

        // Kendo Table Clerks Index
        public async Task<IActionResult> GetClerks([DataSourceRequest] DataSourceRequest request)
        {
            var kendolekkerbekDbContextClerks = await _clerkService.GetClerks();

            List<IndexViewModel> ClerksVMList = new List<IndexViewModel>();

            foreach (var item in kendolekkerbekDbContextClerks)
            {
                IndexViewModel clerksVM = new IndexViewModel
                {
                    Id = item.Id,
                    FirstName = item.FirstName,
                    LastName = item.LastName,
                    BirthDate = item.BirthDate,
                    Adress = item.Adress,
                    Email = item.Email,
                    PhoneNumber = item.PhoneNumber,
                };
                ClerksVMList.Add(clerksVM);
            }


            JsonResult result = Json(ClerksVMList.ToDataSourceResult(request));
            return result;
        }

        // GET: Cooks/Details/5
        public async Task<IActionResult> CookDetails(int? id)
        {
            if (id == null || await _cookService.GetCooks() == null)
            {
                return NotFound();
            }

            var cook = await _cookService.GetCook(id);
            if (cook == null)
            {
                return NotFound();
            }

            return View(cook);
        }

        // GET: Cooks/Details/5
        public async Task<IActionResult> ClerkDetails(int? id)
        {
            if (id == null || await _clerkService.GetClerks() == null)
            {
                return NotFound();
            }

            var clerk = await _clerkService.GetClerk(id);
            if (clerk == null)
            {
                return NotFound();
            }

            return View(clerk);
        }

        // GET: Cooks/Create

        public IActionResult CookCreate()
        {
            return View();
        }

        // POST: Cooks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CookCreate([Bind("Id,FirstName,LastName,BirthDate,Adress,Email,PhoneNumber,Password")] Cook cook)
        {
            try
            {
                await _cookService.CreateCook(cook);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                //ViewBag.PasswordMessage = "minstens 1 hoofdletter + 1 kleineletter + 1 cijfer + 1 speciale leesteken";
                return RedirectToAction(nameof(CookCreate));
            }

        }

        // GET: Clerks/Create

        public IActionResult ClerkCreate()
        {
            return View();
        }

        // POST: Clerks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClerkCreate([Bind("Id,FirstName,LastName,BirthDate,Adress,Email,PhoneNumber,Password")] Clerk clerk)
        {
            try
            {
                await _clerkService.CreateClerk(clerk);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                //ViewBag.PasswordMessage = "minstens 1 hoofdletter + 1 kleineletter + 1 cijfer + 1 speciale leesteken";
                return RedirectToAction(nameof(ClerkCreate));
            }

        }

        // GET: Cooks/Edit/5
        public async Task<IActionResult> CookEdit(int? id)
        {
            if (id == null || await _cookService.GetCooks() == null)
            {
                return NotFound();
            }

            var cook = await _cookService.GetCook(id);
            if (cook == null)
            {
                return NotFound();
            }
            return View(cook);
        }

        // POST: Cooks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CookEdit(int id, [Bind("Id,FirstName,LastName,BirthDate,Adress,Email,PhoneNumber,IdentityUserId")] Cook cook)
        {
            if (id != cook.Id)
            {
                return NotFound();
            }

            try
            {
                await _cookService.EditCook(cook);
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CookExists(cook.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
        }

        // GET: Clerks/Edit/5
        public async Task<IActionResult> ClerkEdit(int? id)
        {
            if (id == null || await _clerkService.GetClerks() == null)
            {
                return NotFound();
            }

            var clerk = await _clerkService.GetClerk(id);
            if (clerk == null)
            {
                return NotFound();
            }
            return View(clerk);
        }

        // POST: Clerks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClerkEdit(int id, [Bind("Id,FirstName,LastName,BirthDate,Adress,Email,PhoneNumber,IdentityUserId")] Clerk clerk)
        {
            if (id != clerk.Id)
            {
                return NotFound();
            }

            try
            {
                await _clerkService.EditClerk(clerk);
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ClerkExists(clerk.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
        }

        // GET: Cooks/Delete/5
        public async Task<IActionResult> CookDelete(int? id)
        {
            if (id == null || await _cookService.GetCooks() == null)
            {
                return NotFound();
            }

            var cook = await _cookService.GetCook(id);
            if (cook == null)
            {
                return NotFound();
            }

            return View(cook);
        }

        // POST: Cooks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CookDelete(int id)
        {
            if (await _cookService.GetCooks() == null)
            {
                return Problem("Entity set 'LekkerbekDbContext.Cooks'  is null.");
            }
            var cook = await _cookService.GetCook(id);
            if (cook != null)
            {
                await _cookService.DeleteCook(cook);
                return RedirectToAction(nameof(Index));
            }

            return View(cook);
        }

        // GET: Clerks/Delete/5
        public async Task<IActionResult> ClerkDelete(int? id)
        {
            if (id == null || await _clerkService.GetClerks() == null)
            {
                return NotFound();
            }

            var clerk = await _clerkService.GetClerk(id);
            if (clerk == null)
            {
                return NotFound();
            }

            return View(clerk);
        }

        // POST: Clerks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClerkDelete(int id)
        {
            if (await _clerkService.GetClerks() == null)

Lekkerbek.Web/Views/Employees/ClerkCreate.cshtml
@model Lekkerbek.Web.Models.Entities.Clerk

@{
    ViewData["Title"] = "Aanmaken clerk";
}

<h1>Aanmaken</h1>

<h4>Clerk</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ClerkCreate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Aanmaken" class="btn btn-primary mt-2" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Terug naar de lijst</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lekkerbek.Web/Views/Employees/ClerkDelete.cshtml
@model Lekkerbek.Web.Models.Entities.Clerk

@{
    ViewData["Title"] = "Verwijderen Clerk";
}

<h1>Verwijderen</h1>

<h3>Bent u zeker dat u deze clerk wilt verwijderen?</h3>
<div>
    <h4>Clerk</h4>
    <hr />
    <dl class="row">       
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
    
    <form asp-action="ClerkDelete">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="IdentityUserId" />
        <input type="submit" value="Verwijderen" class="btn btn-danger" /> |
        <a asp-action="Index">Terug naar de lijst</a>
    </form>
</div>

Lekkerbek.Web/Views/Employees/ClerkDetails.cshtml
@model Lekkerbek.Web.Models.Entities.Clerk

@{
    ViewData["Title"] = "Details clerk";
}

<h1>Details</h1>

<div>
    <h4>Clerk</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="ClerkEdit" asp-route-id="@Model?.Id">Aanpassen</a> |
    <a asp-action="Index">Terug naar de lijst</a>
</div>

Lekkerbek.Web/Views/Employees/ClerkEdit.cshtml
@model Lekkerbek.Web.Models.Entities.Clerk

@{
    ViewData["Title"] = "Aanpassen clerk";
}

<h1>Aanpassen</h1>

<h4>Clerk</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ClerkEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="IdentityUserId" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Bewaren" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Terug naar de lijst</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lekkerbek.Web/Views/Employees/CookCreate.cshtml
@model Lekkerbek.Web.Models.Entities.Cook

@{
    ViewData["Title"] = "Aanmaken kok";
}

<h1>Aanmaken</h1>

<h4>Kok</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CookCreate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>           
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control"/>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Aanmaken" class="btn btn-primary mt-2" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Terug naar de lijst</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lekkerbek.Web/Views/Employees/CookDelete.cshtml
@model Lekkerbek.Web.Models.Entities.Cook

@{
    ViewData["Title"] = "Verwijderen kok";
}

<h1>Verwijderen</h1>

<h3>Bent u zeker dat u deze kok wilt verwijderen?</h3>
<div>
    <h4>Kok</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
    
    <form asp-action="CookDelete">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="IdentityUserId" />
        <input type="submit" value="Verwijderen" class="btn btn-danger" /> |
        <a asp-action="Index">Terug naar de lijst</a>
    </form>
</div>

Lekkerbek.Web/Views/Employees/CookDetails.cshtml
@model Lekkerbek.Web.Models.Entities.Cook

@{
    ViewData["Title"] = "Details kok";
}

<h1>Details</h1>

<div>
    <h4>Kok</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="CookEdit" asp-route-id="@Model?.Id">Aanpassen</a> |
    <a asp-action="Index">Terug naar de lijst</a>
</div>

Lekkerbek.Web/Views/Employees/Index.cshtml
@using Kendo.Mvc.UI;


@{
    ViewData["Title"] = "Overzicht koks";
}

<h1>Overzicht koks</h1>

<p>
    <a asp-action="CookCreate">Nieuwe kok aanmaken</a>
</p>

<div class="form-group">
    @(
        Html.Kendo().Grid<Lekkerbek.Web.ViewModels.Employees.IndexViewModel>()
        .Name("gridCooks")
        .Columns(columns =>
        {
            columns.Bound(p => p.FirstName);
            columns.Bound(p => p.LastName);
            columns.Bound(p => p.BirthdayString);
            columns.Bound(p => p.Adress);
            columns.Bound(p => p.Email);
            columns.Bound(p => p.PhoneNumber);
            columns.Bound(p => p.Id).Width(10).Title(" ").ClientTemplate(
            "<a class='d-inline k-button k-button-md k-rounded-md k-button-solid k-button-solid-base m-1' href='" +
            Url.Action("CookEdit", "Employees") +
            "/#= Id #'" + "><span class='k-icon k-i-edit'></span></a>"
            );
        })
        .HtmlAttributes(new { style = "height: auto;" })
        .Pageable(pageable => pageable
        .Refresh(true)
        .PageSizes(true)
        .ButtonCount(5))
        .DataSource(dataSource => dataSource
        .Ajax()
        .Read(read => read.Action("GetCooks", "Employees"))
        .Model(model => model.Id(d => d.Id))
        .PageSize(5)
        )
        .Events(e => e.DataBound("onDataBoundCooks"))
        )
</div>

<h1 class='mt-3'>Overzicht clerks</h1>

<p>
    <a asp-action="ClerkCreate">Nieuwe bediende aanmaken</a>
</p>

<div class="form-group">
    @(
        Html.Kendo().Grid<Lekkerbek.Web.ViewModels.Employees.IndexViewModel>()
        .Name("gridClerks")
        .Columns(columns =>
        {
            columns.Bound(p => p.FirstName);
            columns.Bound(p => p.LastName);
            columns.Bound(p => p.BirthdayString);
            columns.Bound(p => p.Adress);
            columns.Bound(p => p.Email);
            columns.Bound(p => p.PhoneNumber);
            columns.Bound(p => p.Id).Width(10).Title(" ").ClientTemplate(
            "<a class='d-inline k-button k-button-md k-rounded-md k-button-solid k-button-solid-base m-1' href='" +
            Url.Action("ClerkEdit", "Employees") +
            "/#= Id #'" + "><span class='k-icon k-i-edit'></span></a>"
            );
        })
        .HtmlAttributes(new { style = "height: auto;" })
        .Pageable(pageable => pageable
        .Refresh(true)
        .PageSizes(true)
        .ButtonCount(5))

        .DataSource(dataSource => dataSource
        .Ajax()
        .Read(read => read.Action("GetClerks", "Employees"))
        .Model(model => model.Id(d => d.Id))
        .PageSize(5)
        )
        .Events(e => e.DataBound("onDataBoundClerks"))
        )
</div>

<script>
    function onDataBoundCooks() {
        $('#gridCooks table tr').dblclick(function (e) {
            var grid = $("#gridCooks").data("kendoGrid");
            var row = $(this);

            var dItem = grid.dataItem(row);
            if (dItem != null) {
                var id = dItem.Id;
                window.location.href = "@Url.Action("CookDetails", "Employees")" + "?id=" + id;
            }
        });
    }
</script>

<script>
    function onDataBoundClerks() {
        $('#gridClerks table tr').dblclick(function (e) {
            var grid = $("#gridClerks").data("kendoGrid");
            var row = $(this);

            var dItem = grid.dataItem(row);
            if (dItem != null) {
                var id = dItem.Id;
                window.location.href = "@Url.Action("ClerkDetails", "Employees")" + "?id=" + id;
            }
        });
    }
</script>